apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: backend
        image: oleksanddra/backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mern-config
        - secretRef:
            name: mern-secret
